workflows:
  fvm-workflow:
    name: FVM workflow
    working_directory: kali
    scripts:
      - name: Install FVM
        script: |
          brew tap leoafarias/fvm  
          brew install fvm
          fvm install 3.41.4 
          fvm use 3.41.4 